import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.scss";

const myFont = localFont({
  src: './D-DIN.otf',
})

export const metadata: Metadata = {
  title: "The Last of Us Part 2 Daily runs seed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.className}`}>
        {children}
      </body>
    </html>
  );
}
